creating arrays from python list objects

In [3]:
import numpy as np

In [4]:
list_one = [1, 2, 3]
array_one = np.array(list_one)
array_one

array([1, 2, 3])

In [5]:
list_two = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_two = np.array(list_two)
array_two

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Creating arrays from arange method

In [6]:
array_three = np.arange(0,11)
array_three

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
array_four = np.arange(0, 11, 2)
array_four

array([ 0,  2,  4,  6,  8, 10])

Zeros and Ones arrays

In [8]:
array_five = np.zeros(4)
array_five

array([0., 0., 0., 0.])

In [9]:
array_six = np.zeros((4,6))
array_six

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
array_seven = np.ones(3)
array_seven

array([1., 1., 1.])

In [11]:
array_eight = np.ones((2, 5))
array_eight

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Creating arrays with linspace to get evenly spaced points from a starting point to an endpoint

In [12]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

creating an identity matrix

In [13]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Using the random libraries with numpy

In [14]:
np.random.rand(5)

array([0.5833121 , 0.35315922, 0.26406766, 0.51212107, 0.43703437])

In [15]:
np.random.rand(4, 5)

array([[0.25615858, 0.11523931, 0.87359752, 0.76548459, 0.85963926],
       [0.52127377, 0.26576106, 0.20381452, 0.08338511, 0.29272817],
       [0.36371567, 0.82934407, 0.44538527, 0.09793459, 0.9450458 ],
       [0.34394203, 0.89724877, 0.36339192, 0.56430957, 0.46644952]])

In [16]:
np.random.randn(4)

array([ 0.21004166,  0.64954899,  2.99964019, -0.32948331])

In [17]:
np.random.randn(2,4)

array([[ 0.9480414 ,  1.39728661,  1.5387323 , -0.94423696],
       [-1.26717272,  0.48519609, -0.59161855, -1.68976923]])

In [18]:
np.random.randint(2, 20, 10)

array([ 9, 11, 19,  2,  9, 10, 16, 16, 10,  2])

using the reshape method

In [19]:
my_arr = np.arange(0, 50)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
my_arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Using the max, min, argmax, shape, dtype and argmin

In [21]:
rand_arr = np.random.randint(0, 50, 10)
rand_arr

array([ 4, 30, 45, 47, 41, 39,  8,  6, 31, 40])

In [22]:
rand_arr.max()

47

In [23]:
rand_arr.min()

4

In [24]:
rand_arr.argmin()

0

In [25]:
rand_arr.argmax()

3

In [26]:
my_arr.shape

(50,)

In [27]:
my_arr.dtype

dtype('int32')

Numpy arrays indexing

In [28]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
index_slice = arr[5]
index_slice

5

In [30]:
range_slice = arr[3:]
range_slice

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
range_slice_1 = arr[:7]
range_slice_1

array([0, 1, 2, 3, 4, 5, 6])

Array broadcasting

In [32]:
arr[4:8] = 10000
arr

array([    0,     1,     2,     3, 10000, 10000, 10000, 10000,     8,
           9,    10])

In [33]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [36]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100, 100])

broadcasting affects the original array also. But arr.copy() is essential for storing the original array

In [37]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [38]:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

Indexing a 2D arrays

In [39]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[0]

array([ 5, 10, 15])

In [41]:
arr_2d[0][1]

10

In [42]:
arr_2d[1]

array([20, 25, 30])

In [43]:
arr_2d[1][2]

30

In [45]:
arr_2d[2,1]

40

In [48]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [49]:
arr_2d[:, 1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

Using comparison operators on arrays

In [50]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
bool_array = arr>5
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [54]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [56]:
arr_2d_1 = np.arange(50).reshape(5,10)
arr_2d_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
arr_2d_1[1:, 4:]

array([[14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29],
       [34, 35, 36, 37, 38, 39],
       [44, 45, 46, 47, 48, 49]])

Numpy Operations

In [59]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Adding arrays

In [60]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

subtracting arrays

In [62]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Multiplying arrays

In [63]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

dividing arrays

In [66]:
arr % arr

C:\Users\kevin\AppData\Local\Temp\ipykernel_5964\2907441788.py:1: RuntimeWarning: divide by zero encountered in remainder
  arr % arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Using array scalars

In [67]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [68]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [69]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

universal operations

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [71]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

Numpy Exercises

Creating an array of ten zeros

In [73]:
ten_zeros = np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Creating an array of ten ones

In [74]:
ten_ones = np.ones(10)
ten_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

creating an array of ten  fives

In [75]:
ten_fives = np.ones(10) * 5
ten_fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

creating an array of integers from ten to fifty

In [76]:
ten_to_fifty = np.arange(10,51)
ten_to_fifty

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

create an array of even integers from ten to fifty

In [77]:
even_ints = np.arange(10,51,2)
even_ints

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Creating a 3 * 3 matrix from values ranging from zero to eight

In [79]:
zero_to_eight = np.arange(0,9).reshape(3,3)
zero_to_eight

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

creating a 3 * 3 identity matrix

In [80]:
identity_matr = np.eye(3)
identity_matr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

using numpy to generate random numbers between zero and one

In [84]:
random_ints = np.random.rand(1)
random_ints

array([0.64197348])

Generating an array of 25 random numbers sampled from a standard normal distribution

In [85]:
array_snd = np.random.randn(25)
array_snd

array([-0.70833041, -0.23721028,  1.13535474,  0.01219032,  0.1864259 ,
        1.85204527, -1.68035888,  1.48573228,  1.13338927, -1.81992297,
        1.35797432, -0.29758224,  1.63011974, -0.16518366, -0.11651793,
        0.58791054,  0.67877795,  2.86758845,  1.52443616, -1.00652795,
       -0.79871938, -1.51375682, -0.48721915,  0.28033444,  0.96569583])

Creating a matrix of linearly spaces numbers

In [94]:
np.arange(1.,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Creating an array of twenty linearly spaced points between zero and one

In [95]:
linear_arr = np.linspace(0,1,20)
linear_arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Numpy Indexing exercises

In [97]:
matr = np.arange(1,26).reshape(5,5)
matr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
sliced_mtr = matr[2:, 1:]
sliced_mtr

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [101]:
sliced_mtr_1 = matr[3,4]
sliced_mtr_1

20

In [105]:
matr[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [106]:
matr[4]

array([21, 22, 23, 24, 25])

Getting the sum of the matrix

In [108]:
matr.sum()

325

Getting the standard deviation of the matrix

In [109]:
matr.std()

7.211102550927978

Getting the sum of all columns in the matrix

In [110]:
matr.sum(axis=0)

array([55, 60, 65, 70, 75])